### ISSUE TITLE
Documentation for header

### ISSUE THREAD

**Issue by bradisbell** [floatdrop/express-request-id#1]
This is helpful middleware.  Just a note... it wasn't clear what header was being set without digging into the code.  Maybe the README could have something that mentions `X-Request-Id`, and clarifies that the header is a response header and not something tacked onto the existing request headers.

**Comment by floatdrop** [comment]
Thanks. Clarified thing about header in top of readme.

**Comment by lonix1** [comment]
The docs are still misleading... Took me a while to deduce:

- a uuid is generated
- it is added to a new `id` property on the express `req` object
- it is added to a new `X-Request-Id` header on the express `res` object

If the above is correct then it should be used in the docs.
