### ISSUE TITLE
[Question] Use cases?

### ISSUE THREAD

**Issue by lonix1** [floatdrop/express-request-id#11]
Possibly a silly question, but...

Why would I use this library - what use case does it apply to?

**Comment by jybleau** [comment]
My use case: Help in linking different log entries to each other. Then a request log and its associated Response log would have the same id.

Example from this article: [https://medium.com/@tobydigz/logging-in-a-node-express-app-with-morgan-and-bunyan-30d9bf2c07a](https://medium.com/@tobydigz/logging-in-a-node-express-app-with-morgan-and-bunyan-30d9bf2c07a)

**Comment by lonix1** [comment]
Makes good sense, thanks @jybleau

**Comment by lonix1** [comment]
Some more very good use cases in this [readme](https://www.npmjs.com/package/connect-uuid).
