### ISSUE TITLE
[Feature request] Warn about misuse

### ISSUE THREAD

**Issue by Asaf-S** [floatdrop/express-request-id#16]
If someone uses the library like this:
```
import express_request_id from 'express-request-id';
express().use(express_request_id) // Note: 'express_request_id' and not 'express_request_id()'
```
instead of like this:
```
import express_request_id from 'express-request-id';
express().use(express_request_id())
```

The library should recognize the input as express's input - and output a warning to console.error().
Otherwise, the requests timeout with no reason/error.

Great library, thanks!

**Comment by floatdrop** [comment]
This can be checked by typings with TypeScript.
