### ISSUE TITLE
options.setHeader doesn't accept falsy values

### ISSUE THREAD

**Issue by bradisbell** [floatdrop/express-request-id#2]
It doesn't appear that `options.setHeader` accepts falsy values as currently written:

```
options.setHeader = options.setHeader !== false;
```

Perhaps this line could be modified?

**Comment by floatdrop** [comment]
Perhaps, but why?

**Comment by bradisbell** [comment]
I think it is expected that option values allow truthy/falsy values unless there is a specific reason not to.  I hit this issue when using your code.  It didn't take long to figure out, but I'm sure others will run into this as well.  Just a suggestion.
