### ISSUE TITLE
Release 2.0.0 introduced breaking changes without notice

### ISSUE THREAD

**Issue by iondrimba** [floatdrop/express-request-id#23]
Hi there, I was trying to update express-request-id from 1.4.1 to 2.0.1 and noticed that the module does not work with commonjs anymore.

Is there a way around this or do I need to update module handling from commonjs to es6 modules?

**Comment by jeremy-london** [comment]
Ran into this problem as well. Staying at 1.4.1 for now

Async import works

```
const api = express();

(async () => await import('express-request-id'))().then(requestID => {
  api.use(requestID.default({ attributeName: 'uuid' }));
});
```

**Comment by jeremy-london** [comment]
Ran into this problem as well.. sticking with 1.4.1 until updated

**Comment by grahamb** [comment]
Just his this as well. Converting from CJS to ESM is a massive breaking change and should have been a major version release.

**Comment by funtuan** [comment]
+1
ES modules is not supported
sticking with 1.4.1 until updated

**Comment by nealoke** [comment]
This is the most annoying thing ever 😅, sticking with 1.4.1 as well until updated.

**Comment by darbio** [comment]
Still not supported...

**Comment by floatdrop** [comment]
Node.JS supports es6 modules from 12 lts version (I think). CJS version is not planned for this module.

**Comment by floatdrop** [comment]
@iondrimba you can read [this gist about ESM packages](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

**Comment by iondrimba** [comment]
Thanks @floatdrop
