### ISSUE TITLE
TypeScript definition not found

### ISSUE THREAD

**Issue by LukeSavefrogs** [floatdrop/express-request-id#25]
Hi, 
I see that the Type are not installed with v. 2.0.1 and i get `ts(7016)`
![image](https://user-images.githubusercontent.com/33452387/166169128-701d1222-49df-4a0a-a985-121ae7947f16.png)

**Comment by jfairley** [comment]
Merged, but unreleased as far as I can tell. 

https://github.com/floatdrop/express-request-id/pull/22

**Comment by floatdrop** [comment]
Released in v.3.0.0

**Comment by LukeSavefrogs** [comment]
> Released in v.3.0.0

Thank you!
